namespace ChequeRequisiontService.Core.Dto.SummaryReport;

public class ConsumptionReportDto
{

    public DateOnly? RequestDate { get; set; } = null;
    public int? Csbcd5Books { get; set; }
    public int? Csbcd5Leaves { get; set; }
    public int? Csbcd10Books { get; set; }
    public int? Csbcd10Leaves { get; set; }
    public int? Csbcd20Books { get; set; }
    public int? Csbcd20Leaves { get; set; }
    public int? Csbcd50Books { get; set; }
    public int? Csbcd50Leaves { get; set; }
    public int? Isbcd5Books { get; set; }
    public int? Isbcd5Leaves { get; set; }
    public int? Isbcd10Books { get; set; }
    public int? Isbcd10Leaves { get; set; }
    public int? Isbcd20Books { get; set; }
    public int? Isbcd20Leaves { get; set; }
    public int? Isbcd50Books { get; set; }
    public int? Isbcd50Leaves { get; set; }
    public int? Psbcd10Books { get; set; }
    public int? Psbcd10Leaves { get; set; }
    public int? Psbcd20Books { get; set; }
    public int? Psbcd20Leaves { get; set; }
    public int? Psbcd50Books { get; set; }
    public int? Psbcd50Leaves { get; set; }
    public int? ConSb10Books { get; set; }
    public int? ConSb10Leaves { get; set; }
    public int? ConSb20Books { get; set; }
    public int? ConSb20Leaves { get; set; }
    public int? ConSb25Books { get; set; }
    public int? ConSb25Leaves { get; set; }
    public int? IslmSb10Books { get; set; }
    public int? IslmSb10Leaves { get; set; }
    public int? IslmSb20Books { get; set; }
    public int? IslmSb20Leaves { get; set; }
    public int? IslmSb25Books { get; set; }
    public int? IslmSb25Leaves { get; set; }
    public int? ConSba10Books { get; set; }
    public int? ConSba10Leaves { get; set; }
    public int? ConMsd10Books { get; set; }
    public int? ConMsd10Leaves { get; set; }
    public int? ConMsd50Books { get; set; }
    public int? ConMsd50Leaves { get; set; }
    public int? ConMsa10Books { get; set; }
    public int? ConMsa10Leaves { get; set; }
    public int? ConMsa20Books { get; set; }
    public int? ConMsa20Leaves { get; set; }
    public int? ConCd10Books { get; set; }
    public int? ConCd10Leaves { get; set; }
    public int? ConCd25Books { get; set; }
    public int? ConCd25Leaves { get; set; }
    public int? IslmCd25Books { get; set; }
    public int? IslmCd25Leaves { get; set; }
    public int? ConCd50Books { get; set; }
    public int? ConCd50Leaves { get; set; }
    public int? IslmCd50Books { get; set; }
    public int? IslmCd50Leaves { get; set; }
    public int? ConCd100Books { get; set; }
    public int? ConCd100Leaves { get; set; }
    public int? ConCda25Books { get; set; }
    public int? ConCda25Leaves { get; set; }
    public int? ConAcd25Books { get; set; }
    public int? ConAcd25Leaves { get; set; }
    public int? ConAcd50Books { get; set; }
    public int? ConAcd50Leaves { get; set; }
    public int? ConAcd100Books { get; set; }
    public int? ConAcd100Leaves { get; set; }
    public int? ConAwca20Books { get; set; }
    public int? ConAwca20Leaves { get; set; }
    public int? ConAwca50Books { get; set; }
    public int? ConAwca50Leaves { get; set; }
    public int? ConAwca100Books { get; set; }
    public int? ConAwca100Leaves { get; set; }
    public int? ConAwcd25Books { get; set; }
    public int? ConAwcd25Leaves { get; set; }
    public int? ConSna25Books { get; set; }
    public int? ConSna25Leaves { get; set; }
    public int? ConSnd25Books { get; set; }
    public int? ConSnd25Leaves { get; set; }
    public int? ConSnd50Books { get; set; }
    public int? ConSnd50Leaves { get; set; }
    public int? ConSnd100Books { get; set; }
    public int? ConSnd100Leaves { get; set; }
    public int? ConMsnd25Books { get; set; }
    public int? ConMsnd25Leaves { get; set; }
    public int? ConPo50Books { get; set; }
    public int? ConPo50Leaves { get; set; }
    public int? ConPo100Books { get; set; }
    public int? ConPo100Leaves { get; set; }
    public int? ConCc50Books { get; set; }
    public int? ConCc50Leaves { get; set; }
    public int? ConCc100Books { get; set; }
    public int? ConCc100Leaves { get; set; }
    public int? ConPoa50Books { get; set; }
    public int? ConPoa50Leaves { get; set; }
    public int? ConPoi50Books { get; set; }
    public int? ConPoi50Leaves { get; set; }
    public int? ConFdr100Books { get; set; }
    public int? ConFdr100Leaves { get; set; }
    public int? ConFdr50Books { get; set; }
    public int? ConFdr50Leaves { get; set; }
    public int? ConMtdr25Books { get; set; }
    public int? ConMtdr25Leaves { get; set; }
    public int? ConMtdr50Books { get; set; }
    public int? ConMtdr50Leaves { get; set; }

    public int? TotalBooks { get; set; }
    public int? TotalLeaves { get; set; }
}

